os: osx
osx_image: xcode11.2
language: swift
xcode_project: ExampleMVVM.xcodeproj # path to your xcodeproj folder
xcode_scheme: ExampleMVVM
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro Max
